### ISSUE TITLE
"Cannot set property defaults of #<n>" error while integrating GrapesJS-blocks-boostrap4 plugin

### ISSUE THREAD

**Issue by dannickstark** [kaoz70/grapesjs-blocks-bootstrap4#70]
Hi there.
I am trying to add grapesjs-blocks-bootstrap4 plugin in my grapesjs editor in reactjs. When I try adding it, I get the following error.
`TypeError: Cannot set property defaults of #<n> which has only a getter
    at eval (grapes.min.js?a826:2:1)
    at Module.It (grapes.min.js?a826:2:1)
    at Function.$ [as extend] (grapes.min.js?a826:2:1)
    at vr (grapesjs-blocks-bootstrap4.min.js?5902:11:1)
    at eval (grapesjs-blocks-bootstrap4.min.js?5902:11:1)
    at eval (grapes.min.js?a826:2:1)`

I tried deleting the node modules and installing them again, but still had the same issue. Thank you for your help in advance.

**Comment by matthewmichel** [comment]
I'm also getting this issue

**Comment by srivatsan2607** [comment]
Hi, I am getting the same error as well. Any luck in finding the solution?
It was not happening with grapesjs previous version.

**Comment by dannickstark** [comment]
I didn't find any solution

**Comment by dannickstark** [comment]
> Hi, I am getting the same error as well. Any luck in finding the solution? It was not happening with grapesjs previous version.

I didn't find any solution

**Comment by srivatsan2607** [comment]
Oh okay, any workaround that can be done?

**Comment by allamo123** [comment]
@kaoz70 @dsgh @srivatsan2607 @dannickstark @matthewmichel 
hello, do anyone solve this issue or have a solution.

**Comment by allamo123** [comment]
`npm i grapesjs@0.17.4`
i hope these solve the proplem

**Comment by chaegumi** [comment]
https://github.com/chaegumi/grapesjs-blocks-bootstrap4

Wrong code

```javascript
domc.addType('alert', {
        model: textModel.extend({
            defaults: Object.assign({}, textModel.prototype.defaults, {
                'custom-name': 'Alert',
                tagName: 'div',
                classes: ['alert'],
                traits: [
                    {
                        type: 'class_select',
                        options: [
                            {value: '', name: 'None'},
                            ... contexts.map(function(v) { return {value: 'alert-'+v, name: capitalize(v)} })
                        ],
                        label: 'Context'
                    }
                ].concat(textModel.prototype.defaults.traits)
            })
        }, {
            isComponent(el) {
                if(el && el.classList && el.classList.contains('alert')) {
                    return {type: 'alert'};
                }
            }
        }),
        view: textView
    });
```

Correct code

```javascript
    domc.addType('alert', {
        extend: 'text',
        model: {
            defaults: Object.assign({}, textModel.prototype.defaults, {
                'custom-name': 'Alert',
                tagName: 'div',
                classes: ['alert'],
                traits: [
                    {
                        type: 'class_select',
                        options: [
                            { value: '', name: 'None' },
                            ...contexts.map(function (v) { return { value: 'alert-' + v, name: capitalize(v) } })
                        ],
                        label: 'Context'
                    }
                ].concat(textModel.prototype.defaults.traits)
            })
        },
        isComponent(el) {
            if (el && el.classList && el.classList.contains('alert')) {
                return { type: 'alert' };
            }
        },
        view: textView
    });
```

**Comment by handhikadj** [comment]
getting this issue on v0.20.4. showing `TypeError: Cannot assign to read only property 'defaults' of object '[object Object]` on Chrome

**Comment by jaywilburn** [comment]
Is this still a problem for anyone? Did anyone find a workaround for it? If you ended up removing this, what was your alternative?

**Comment by shadab97** [comment]
still same issue

`bundle.js:10 Uncaught TypeError: Cannot set property defaults of #<e> which has only a getter`

with 
"grapesjs": "^0.21.13",
"grapesjs-blocks-basic": "^1.0.2",
"grapesjs-blocks-bootstrap4": "^0.2.3"

**Comment by kaoz70** [comment]
Could you please see if v0.2.5 fixes this?

**Comment by toiyabe** [comment]
> Could you please see if v0.2.5 fixes this?

Fixed for me :)

**Comment by chetan-bbc** [comment]
Getting below error, when am trying to extend video's default model. Do we have a fix for this ? Thanks in advance.

```
ERROR TypeError: Cannot set property defaults of [object Object] which has only a getter
    at grapes.mjs:25386:58
    at Module.create (grapes.mjs:25433:18)
    at Function.extend (grapes.mjs:2875:29)
    at gjsPluginBrightcove (brightcove.ts:424:29)
    at grapes.mjs:72567:9
    at Array.forEach (<anonymous>)
```

**Comment by kaoz70** [comment]
Fixed in #93 

@chetan-bbc  please create a new ticket for this if needed and with more details.
